// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Monitor struct {
	ID                  pgtype.UUID        `json:"id"`
	ServiceID           pgtype.UUID        `json:"service_id"`
	Name                string             `json:"name"`
	Type                string             `json:"type"`
	Url                 *string            `json:"url"`
	Host                *string            `json:"host"`
	Port                *int32             `json:"port"`
	IntervalSeconds     int32              `json:"interval_seconds"`
	TimeoutMs           int32              `json:"timeout_ms"`
	RetryCount          int32              `json:"retry_count"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	DegradedThresholdMs *int32             `json:"degraded_threshold_ms"`
	HttpMethod          *string            `json:"http_method"`
	HttpExpectedStatus  *int32             `json:"http_expected_status"`
	Enabled             bool               `json:"enabled"`
	NextCheckAt         pgtype.Timestamptz `json:"next_check_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt          pgtype.Timestamptz `json:"archived_at"`
}

type Service struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
}
