// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveService(ctx context.Context, id pgtype.UUID) error
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	GetServiceByID(ctx context.Context, id pgtype.UUID) (Service, error)
	ListServices(ctx context.Context) ([]Service, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
}

var _ Querier = (*Queries)(nil)
