// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveService = `-- name: ArchiveService :exec
UPDATE services
SET archived_at = now()
WHERE id = $1
`

func (q *Queries) ArchiveService(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveService, id)
	return err
}

const createService = `-- name: CreateService :one
INSERT INTO services (name, description)
VALUES ($1, $2)
RETURNING id, name, description, status, created_at, archived_at
`

type CreateServiceParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService, arg.Name, arg.Description)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, name, description, status, created_at, archived_at FROM services
WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetServiceByID(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, name, description, status, created_at, archived_at FROM services
WHERE archived_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = $2, description = $3, status = $4
WHERE id = $1
RETURNING id, name, description, status, created_at, archived_at
`

type UpdateServiceParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
