// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (user_id, action, resource, resource_id, ip, user_agent, diff)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, action, resource, resource_id, ip, user_agent, diff, created_at
`

type InsertAuditLogParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Action     string      `json:"action"`
	Resource   string      `json:"resource"`
	ResourceID *string     `json:"resource_id"`
	Ip         *string     `json:"ip"`
	UserAgent  *string     `json:"user_agent"`
	Diff       []byte      `json:"diff"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Ip,
		arg.UserAgent,
		arg.Diff,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Action,
		&i.Resource,
		&i.ResourceID,
		&i.Ip,
		&i.UserAgent,
		&i.Diff,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, user_id, action, resource, resource_id, ip, user_agent, diff, created_at FROM audit_log ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListAuditLog(ctx context.Context, limit int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Ip,
			&i.UserAgent,
			&i.Diff,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByResource = `-- name: ListAuditLogByResource :many
SELECT id, user_id, action, resource, resource_id, ip, user_agent, diff, created_at FROM audit_log
WHERE resource = $1 AND resource_id = $2
ORDER BY created_at DESC
`

type ListAuditLogByResourceParams struct {
	Resource   string  `json:"resource"`
	ResourceID *string `json:"resource_id"`
}

func (q *Queries) ListAuditLogByResource(ctx context.Context, arg ListAuditLogByResourceParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogByResource, arg.Resource, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Ip,
			&i.UserAgent,
			&i.Diff,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
