// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (service_id, monitor_id, title, severity)
VALUES ($1, $2, $3, $4)
RETURNING id, service_id, monitor_id, title, severity, status, resolved_at, created_at, updated_at
`

type CreateIncidentParams struct {
	ServiceID pgtype.UUID `json:"service_id"`
	MonitorID pgtype.UUID `json:"monitor_id"`
	Title     string      `json:"title"`
	Severity  string      `json:"severity"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.ServiceID,
		arg.MonitorID,
		arg.Title,
		arg.Severity,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.MonitorID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncidentByID = `-- name: GetIncidentByID :one
SELECT id, service_id, monitor_id, title, severity, status, resolved_at, created_at, updated_at FROM incidents WHERE id = $1
`

func (q *Queries) GetIncidentByID(ctx context.Context, id pgtype.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, getIncidentByID, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.MonitorID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenIncidentForMonitor = `-- name: GetOpenIncidentForMonitor :one
SELECT id, service_id, monitor_id, title, severity, status, resolved_at, created_at, updated_at FROM incidents
WHERE monitor_id = $1 AND status = 'open'
LIMIT 1
`

func (q *Queries) GetOpenIncidentForMonitor(ctx context.Context, monitorID pgtype.UUID) (Incident, error) {
	row := q.db.QueryRow(ctx, getOpenIncidentForMonitor, monitorID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.MonitorID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllIncidents = `-- name: ListAllIncidents :many
SELECT id, service_id, monitor_id, title, severity, status, resolved_at, created_at, updated_at FROM incidents ORDER BY created_at DESC
`

func (q *Queries) ListAllIncidents(ctx context.Context) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listAllIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.MonitorID,
			&i.Title,
			&i.Severity,
			&i.Status,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentsByService = `-- name: ListIncidentsByService :many
SELECT id, service_id, monitor_id, title, severity, status, resolved_at, created_at, updated_at FROM incidents WHERE service_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListIncidentsByService(ctx context.Context, serviceID pgtype.UUID) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.MonitorID,
			&i.Title,
			&i.Severity,
			&i.Status,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveIncident = `-- name: ResolveIncident :one
UPDATE incidents
SET status = 'resolved', resolved_at = $2, updated_at = now()
WHERE id = $1
RETURNING id, service_id, monitor_id, title, severity, status, resolved_at, created_at, updated_at
`

type ResolveIncidentParams struct {
	ID         pgtype.UUID        `json:"id"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

func (q *Queries) ResolveIncident(ctx context.Context, arg ResolveIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, resolveIncident, arg.ID, arg.ResolvedAt)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.MonitorID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIncident = `-- name: UpdateIncident :one
UPDATE incidents
SET title = $2, severity = $3, status = $4, updated_at = now()
WHERE id = $1
RETURNING id, service_id, monitor_id, title, severity, status, resolved_at, created_at, updated_at
`

type UpdateIncidentParams struct {
	ID       pgtype.UUID `json:"id"`
	Title    string      `json:"title"`
	Severity string      `json:"severity"`
	Status   string      `json:"status"`
}

func (q *Queries) UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error) {
	row := q.db.QueryRow(ctx, updateIncident,
		arg.ID,
		arg.Title,
		arg.Severity,
		arg.Status,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.MonitorID,
		&i.Title,
		&i.Severity,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
