// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incident_updates.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncidentUpdate = `-- name: CreateIncidentUpdate :one
INSERT INTO incident_updates (incident_id, status, message)
VALUES ($1, $2, $3)
RETURNING id, incident_id, status, message, created_at
`

type CreateIncidentUpdateParams struct {
	IncidentID pgtype.UUID `json:"incident_id"`
	Status     string      `json:"status"`
	Message    string      `json:"message"`
}

func (q *Queries) CreateIncidentUpdate(ctx context.Context, arg CreateIncidentUpdateParams) (IncidentUpdate, error) {
	row := q.db.QueryRow(ctx, createIncidentUpdate, arg.IncidentID, arg.Status, arg.Message)
	var i IncidentUpdate
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
	)
	return i, err
}

const listIncidentUpdates = `-- name: ListIncidentUpdates :many
SELECT id, incident_id, status, message, created_at FROM incident_updates
WHERE incident_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListIncidentUpdates(ctx context.Context, incidentID pgtype.UUID) ([]IncidentUpdate, error) {
	rows, err := q.db.Query(ctx, listIncidentUpdates, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentUpdate{}
	for rows.Next() {
		var i IncidentUpdate
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
