// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance_windows.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveMaintenanceWindow = `-- name: ArchiveMaintenanceWindow :exec
UPDATE maintenance_windows SET archived_at = now() WHERE id = $1
`

func (q *Queries) ArchiveMaintenanceWindow(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveMaintenanceWindow, id)
	return err
}

const createMaintenanceWindow = `-- name: CreateMaintenanceWindow :one
INSERT INTO maintenance_windows (service_id, title, description, starts_at, ends_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, service_id, title, description, starts_at, ends_at, created_at, archived_at
`

type CreateMaintenanceWindowParams struct {
	ServiceID   pgtype.UUID        `json:"service_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) CreateMaintenanceWindow(ctx context.Context, arg CreateMaintenanceWindowParams) (MaintenanceWindow, error) {
	row := q.db.QueryRow(ctx, createMaintenanceWindow,
		arg.ServiceID,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getMaintenanceWindowByID = `-- name: GetMaintenanceWindowByID :one
SELECT id, service_id, title, description, starts_at, ends_at, created_at, archived_at FROM maintenance_windows WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetMaintenanceWindowByID(ctx context.Context, id pgtype.UUID) (MaintenanceWindow, error) {
	row := q.db.QueryRow(ctx, getMaintenanceWindowByID, id)
	var i MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const isMaintenanceActiveForService = `-- name: IsMaintenanceActiveForService :one
SELECT EXISTS(
  SELECT 1 FROM maintenance_windows
  WHERE service_id = $1
    AND archived_at IS NULL
    AND starts_at <= now()
    AND ends_at >= now()
) AS active
`

func (q *Queries) IsMaintenanceActiveForService(ctx context.Context, serviceID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isMaintenanceActiveForService, serviceID)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const listActiveForService = `-- name: ListActiveForService :many
SELECT id, service_id, title, description, starts_at, ends_at, created_at, archived_at FROM maintenance_windows
WHERE service_id = $1
  AND archived_at IS NULL
  AND starts_at <= now()
  AND ends_at >= now()
ORDER BY starts_at ASC
`

func (q *Queries) ListActiveForService(ctx context.Context, serviceID pgtype.UUID) ([]MaintenanceWindow, error) {
	rows, err := q.db.Query(ctx, listActiveForService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceWindow{}
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveMaintenanceWindows = `-- name: ListActiveMaintenanceWindows :many
SELECT id, service_id, title, description, starts_at, ends_at, created_at, archived_at FROM maintenance_windows
WHERE archived_at IS NULL
  AND starts_at <= now()
  AND ends_at >= now()
ORDER BY starts_at ASC
`

func (q *Queries) ListActiveMaintenanceWindows(ctx context.Context) ([]MaintenanceWindow, error) {
	rows, err := q.db.Query(ctx, listActiveMaintenanceWindows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceWindow{}
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceWindowsByService = `-- name: ListMaintenanceWindowsByService :many
SELECT id, service_id, title, description, starts_at, ends_at, created_at, archived_at FROM maintenance_windows
WHERE service_id = $1 AND archived_at IS NULL
ORDER BY starts_at DESC
`

func (q *Queries) ListMaintenanceWindowsByService(ctx context.Context, serviceID pgtype.UUID) ([]MaintenanceWindow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceWindowsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceWindow{}
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenanceWindow = `-- name: UpdateMaintenanceWindow :one
UPDATE maintenance_windows
SET title       = COALESCE($2, title),
    description = COALESCE($3, description),
    starts_at   = COALESCE($4, starts_at),
    ends_at     = COALESCE($5, ends_at)
WHERE id = $1 AND archived_at IS NULL
RETURNING id, service_id, title, description, starts_at, ends_at, created_at, archived_at
`

type UpdateMaintenanceWindowParams struct {
	ID          pgtype.UUID        `json:"id"`
	Title       *string            `json:"title"`
	Description *string            `json:"description"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	EndsAt      pgtype.Timestamptz `json:"ends_at"`
}

func (q *Queries) UpdateMaintenanceWindow(ctx context.Context, arg UpdateMaintenanceWindowParams) (MaintenanceWindow, error) {
	row := q.db.QueryRow(ctx, updateMaintenanceWindow,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
