// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	KeyHash    string             `json:"key_hash"`
	Prefix     string             `json:"prefix"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsed   pgtype.Timestamptz `json:"last_used"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Action     string             `json:"action"`
	Resource   string             `json:"resource"`
	ResourceID *string            `json:"resource_id"`
	Ip         *string            `json:"ip"`
	UserAgent  *string            `json:"user_agent"`
	Diff       []byte             `json:"diff"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CheckResult struct {
	ID             pgtype.UUID        `json:"id"`
	MonitorID      pgtype.UUID        `json:"monitor_id"`
	Status         string             `json:"status"`
	ResponseTimeMs *int32             `json:"response_time_ms"`
	Error          *string            `json:"error"`
	CheckedAt      pgtype.Timestamptz `json:"checked_at"`
}

type Incident struct {
	ID         pgtype.UUID        `json:"id"`
	ServiceID  pgtype.UUID        `json:"service_id"`
	MonitorID  pgtype.UUID        `json:"monitor_id"`
	Title      string             `json:"title"`
	Severity   string             `json:"severity"`
	Status     string             `json:"status"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Monitor struct {
	ID                  pgtype.UUID        `json:"id"`
	ServiceID           pgtype.UUID        `json:"service_id"`
	Name                string             `json:"name"`
	Type                string             `json:"type"`
	Url                 *string            `json:"url"`
	Host                *string            `json:"host"`
	Port                *int32             `json:"port"`
	IntervalSeconds     int32              `json:"interval_seconds"`
	TimeoutMs           int32              `json:"timeout_ms"`
	RetryCount          int32              `json:"retry_count"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	DegradedThresholdMs *int32             `json:"degraded_threshold_ms"`
	HttpMethod          *string            `json:"http_method"`
	HttpExpectedStatus  *int32             `json:"http_expected_status"`
	Enabled             bool               `json:"enabled"`
	NextCheckAt         pgtype.Timestamptz `json:"next_check_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ArchivedAt          pgtype.Timestamptz `json:"archived_at"`
}

type NotificationChannel struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Type       string             `json:"type"`
	Config     string             `json:"config"`
	Enabled    bool               `json:"enabled"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type Service struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ArchivedAt   pgtype.Timestamptz `json:"archived_at"`
}

type Webhook struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Url        string             `json:"url"`
	Secret     *string            `json:"secret"`
	Events     []string           `json:"events"`
	Enabled    bool               `json:"enabled"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

type WebhookLog struct {
	ID          pgtype.UUID        `json:"id"`
	WebhookID   pgtype.UUID        `json:"webhook_id"`
	Event       string             `json:"event"`
	StatusCode  *int32             `json:"status_code"`
	Error       *string            `json:"error"`
	DurationMs  *int32             `json:"duration_ms"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
}
