// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitors.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveMonitor = `-- name: ArchiveMonitor :exec
UPDATE monitors SET archived_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) ArchiveMonitor(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveMonitor, id)
	return err
}

const createMonitor = `-- name: CreateMonitor :one
INSERT INTO monitors (
  service_id, name, type, url, host, port,
  interval_seconds, timeout_ms, retry_count,
  degraded_threshold_ms, http_method, http_expected_status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, service_id, name, type, url, host, port, interval_seconds, timeout_ms, retry_count, consecutive_failures, degraded_threshold_ms, http_method, http_expected_status, enabled, next_check_at, created_at, updated_at, archived_at
`

type CreateMonitorParams struct {
	ServiceID           pgtype.UUID `json:"service_id"`
	Name                string      `json:"name"`
	Type                string      `json:"type"`
	Url                 *string     `json:"url"`
	Host                *string     `json:"host"`
	Port                *int32      `json:"port"`
	IntervalSeconds     int32       `json:"interval_seconds"`
	TimeoutMs           int32       `json:"timeout_ms"`
	RetryCount          int32       `json:"retry_count"`
	DegradedThresholdMs *int32      `json:"degraded_threshold_ms"`
	HttpMethod          *string     `json:"http_method"`
	HttpExpectedStatus  *int32      `json:"http_expected_status"`
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, createMonitor,
		arg.ServiceID,
		arg.Name,
		arg.Type,
		arg.Url,
		arg.Host,
		arg.Port,
		arg.IntervalSeconds,
		arg.TimeoutMs,
		arg.RetryCount,
		arg.DegradedThresholdMs,
		arg.HttpMethod,
		arg.HttpExpectedStatus,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Host,
		&i.Port,
		&i.IntervalSeconds,
		&i.TimeoutMs,
		&i.RetryCount,
		&i.ConsecutiveFailures,
		&i.DegradedThresholdMs,
		&i.HttpMethod,
		&i.HttpExpectedStatus,
		&i.Enabled,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getMonitorByID = `-- name: GetMonitorByID :one
SELECT id, service_id, name, type, url, host, port, interval_seconds, timeout_ms, retry_count, consecutive_failures, degraded_threshold_ms, http_method, http_expected_status, enabled, next_check_at, created_at, updated_at, archived_at FROM monitors
WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetMonitorByID(ctx context.Context, id pgtype.UUID) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitorByID, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Host,
		&i.Port,
		&i.IntervalSeconds,
		&i.TimeoutMs,
		&i.RetryCount,
		&i.ConsecutiveFailures,
		&i.DegradedThresholdMs,
		&i.HttpMethod,
		&i.HttpExpectedStatus,
		&i.Enabled,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const incrementConsecutiveFailures = `-- name: IncrementConsecutiveFailures :one
UPDATE monitors
SET consecutive_failures = consecutive_failures + 1, updated_at = now()
WHERE id = $1
RETURNING consecutive_failures
`

func (q *Queries) IncrementConsecutiveFailures(ctx context.Context, id pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementConsecutiveFailures, id)
	var consecutive_failures int32
	err := row.Scan(&consecutive_failures)
	return consecutive_failures, err
}

const listDueMonitors = `-- name: ListDueMonitors :many
SELECT id, service_id, name, type, url, host, port, interval_seconds, timeout_ms, retry_count, consecutive_failures, degraded_threshold_ms, http_method, http_expected_status, enabled, next_check_at, created_at, updated_at, archived_at FROM monitors
WHERE enabled = true
  AND archived_at IS NULL
  AND next_check_at <= now()
ORDER BY next_check_at ASC
LIMIT 100
`

func (q *Queries) ListDueMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listDueMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.Type,
			&i.Url,
			&i.Host,
			&i.Port,
			&i.IntervalSeconds,
			&i.TimeoutMs,
			&i.RetryCount,
			&i.ConsecutiveFailures,
			&i.DegradedThresholdMs,
			&i.HttpMethod,
			&i.HttpExpectedStatus,
			&i.Enabled,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorsByService = `-- name: ListMonitorsByService :many
SELECT id, service_id, name, type, url, host, port, interval_seconds, timeout_ms, retry_count, consecutive_failures, degraded_threshold_ms, http_method, http_expected_status, enabled, next_check_at, created_at, updated_at, archived_at FROM monitors
WHERE service_id = $1 AND archived_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListMonitorsByService(ctx context.Context, serviceID pgtype.UUID) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitorsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Monitor{}
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.Type,
			&i.Url,
			&i.Host,
			&i.Port,
			&i.IntervalSeconds,
			&i.TimeoutMs,
			&i.RetryCount,
			&i.ConsecutiveFailures,
			&i.DegradedThresholdMs,
			&i.HttpMethod,
			&i.HttpExpectedStatus,
			&i.Enabled,
			&i.NextCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetConsecutiveFailures = `-- name: ResetConsecutiveFailures :exec
UPDATE monitors
SET consecutive_failures = 0, updated_at = now()
WHERE id = $1
`

func (q *Queries) ResetConsecutiveFailures(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetConsecutiveFailures, id)
	return err
}

const setNextCheckAt = `-- name: SetNextCheckAt :exec
UPDATE monitors
SET next_check_at = now() + (interval_seconds || ' seconds')::interval
WHERE id = $1
`

func (q *Queries) SetNextCheckAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setNextCheckAt, id)
	return err
}

const updateMonitor = `-- name: UpdateMonitor :one
UPDATE monitors
SET name = $2, url = $3, host = $4, port = $5,
    interval_seconds = $6, timeout_ms = $7, retry_count = $8,
    degraded_threshold_ms = $9, http_method = $10, http_expected_status = $11,
    enabled = $12, updated_at = now()
WHERE id = $1
RETURNING id, service_id, name, type, url, host, port, interval_seconds, timeout_ms, retry_count, consecutive_failures, degraded_threshold_ms, http_method, http_expected_status, enabled, next_check_at, created_at, updated_at, archived_at
`

type UpdateMonitorParams struct {
	ID                  pgtype.UUID `json:"id"`
	Name                string      `json:"name"`
	Url                 *string     `json:"url"`
	Host                *string     `json:"host"`
	Port                *int32      `json:"port"`
	IntervalSeconds     int32       `json:"interval_seconds"`
	TimeoutMs           int32       `json:"timeout_ms"`
	RetryCount          int32       `json:"retry_count"`
	DegradedThresholdMs *int32      `json:"degraded_threshold_ms"`
	HttpMethod          *string     `json:"http_method"`
	HttpExpectedStatus  *int32      `json:"http_expected_status"`
	Enabled             bool        `json:"enabled"`
}

func (q *Queries) UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error) {
	row := q.db.QueryRow(ctx, updateMonitor,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Host,
		arg.Port,
		arg.IntervalSeconds,
		arg.TimeoutMs,
		arg.RetryCount,
		arg.DegradedThresholdMs,
		arg.HttpMethod,
		arg.HttpExpectedStatus,
		arg.Enabled,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.Type,
		&i.Url,
		&i.Host,
		&i.Port,
		&i.IntervalSeconds,
		&i.TimeoutMs,
		&i.RetryCount,
		&i.ConsecutiveFailures,
		&i.DegradedThresholdMs,
		&i.HttpMethod,
		&i.HttpExpectedStatus,
		&i.Enabled,
		&i.NextCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
