// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_channels.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveNotificationChannel = `-- name: ArchiveNotificationChannel :exec
UPDATE notification_channels SET archived_at = now() WHERE id = $1
`

func (q *Queries) ArchiveNotificationChannel(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveNotificationChannel, id)
	return err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :one
INSERT INTO notification_channels (name, type, config)
VALUES ($1, $2, $3)
RETURNING id, name, type, config, enabled, created_at, archived_at
`

type CreateNotificationChannelParams struct {
	Name   string `json:"name"`
	Type   string `json:"type"`
	Config string `json:"config"`
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel, arg.Name, arg.Type, arg.Config)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getNotificationChannelByID = `-- name: GetNotificationChannelByID :one
SELECT id, name, type, config, enabled, created_at, archived_at FROM notification_channels WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetNotificationChannelByID(ctx context.Context, id pgtype.UUID) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannelByID, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listEnabledNotificationChannels = `-- name: ListEnabledNotificationChannels :many
SELECT id, name, type, config, enabled, created_at, archived_at FROM notification_channels WHERE enabled = true AND archived_at IS NULL
`

func (q *Queries) ListEnabledNotificationChannels(ctx context.Context) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listEnabledNotificationChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, name, type, config, enabled, created_at, archived_at FROM notification_channels WHERE archived_at IS NULL ORDER BY created_at
`

func (q *Queries) ListNotificationChannels(ctx context.Context) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.Enabled,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :one
UPDATE notification_channels
SET name    = COALESCE($2, name),
    config  = COALESCE($3, config),
    enabled = COALESCE($4, enabled)
WHERE id = $1
RETURNING id, name, type, config, enabled, created_at, archived_at
`

type UpdateNotificationChannelParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    *string     `json:"name"`
	Config  *string     `json:"config"`
	Enabled *bool       `json:"enabled"`
}

// Partial update: any narg left NULL keeps the existing column value, so the
// handler can omit name/config/enabled independently (e.g. the "toggle
// enabled" switch sends only enabled).
func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateNotificationChannel,
		arg.ID,
		arg.Name,
		arg.Config,
		arg.Enabled,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.Enabled,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
