// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveAPIKey(ctx context.Context, id pgtype.UUID) error
	ArchiveMonitor(ctx context.Context, id pgtype.UUID) error
	ArchiveNotificationChannel(ctx context.Context, id pgtype.UUID) error
	ArchiveService(ctx context.Context, id pgtype.UUID) error
	ArchiveUser(ctx context.Context, id pgtype.UUID) error
	ArchiveWebhook(ctx context.Context, id pgtype.UUID) error
	CountActiveAdmins(ctx context.Context) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error)
	CreateMonitor(ctx context.Context, arg CreateMonitorParams) (Monitor, error)
	CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	GetIncidentByID(ctx context.Context, id pgtype.UUID) (Incident, error)
	GetLatestCheckForMonitor(ctx context.Context, monitorID pgtype.UUID) (CheckResult, error)
	GetMonitorByID(ctx context.Context, id pgtype.UUID) (Monitor, error)
	GetNotificationChannelByID(ctx context.Context, id pgtype.UUID) (NotificationChannel, error)
	GetOpenIncidentForMonitor(ctx context.Context, monitorID pgtype.UUID) (Incident, error)
	GetServiceByID(ctx context.Context, id pgtype.UUID) (Service, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetWebhookByID(ctx context.Context, id pgtype.UUID) (Webhook, error)
	IncrementConsecutiveFailures(ctx context.Context, id pgtype.UUID) (int32, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	InsertCheckResult(ctx context.Context, arg InsertCheckResultParams) (CheckResult, error)
	InsertWebhookLog(ctx context.Context, arg InsertWebhookLogParams) (WebhookLog, error)
	ListAPIKeysByUser(ctx context.Context, userID pgtype.UUID) ([]ApiKey, error)
	ListAllIncidents(ctx context.Context) ([]Incident, error)
	ListAuditLog(ctx context.Context, limit int32) ([]AuditLog, error)
	ListAuditLogByResource(ctx context.Context, arg ListAuditLogByResourceParams) ([]AuditLog, error)
	ListCheckResultsByMonitor(ctx context.Context, arg ListCheckResultsByMonitorParams) ([]CheckResult, error)
	ListDueMonitors(ctx context.Context) ([]Monitor, error)
	ListEnabledNotificationChannels(ctx context.Context) ([]NotificationChannel, error)
	ListIncidentsByService(ctx context.Context, serviceID pgtype.UUID) ([]Incident, error)
	ListMonitorsByService(ctx context.Context, serviceID pgtype.UUID) ([]Monitor, error)
	ListNotificationChannels(ctx context.Context) ([]NotificationChannel, error)
	ListServices(ctx context.Context) ([]Service, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListWebhookLogs(ctx context.Context, arg ListWebhookLogsParams) ([]WebhookLog, error)
	ListWebhooks(ctx context.Context) ([]Webhook, error)
	ListWebhooksByEvent(ctx context.Context, dollar_1 string) ([]Webhook, error)
	ResetConsecutiveFailures(ctx context.Context, id pgtype.UUID) error
	ResolveIncident(ctx context.Context, arg ResolveIncidentParams) (Incident, error)
	SetNextCheckAt(ctx context.Context, id pgtype.UUID) error
	UpdateAPIKeyLastUsed(ctx context.Context, id pgtype.UUID) error
	UpdateIncident(ctx context.Context, arg UpdateIncidentParams) (Incident, error)
	UpdateMonitor(ctx context.Context, arg UpdateMonitorParams) (Monitor, error)
	// Partial update: any narg left NULL keeps the existing column value, so the
	// handler can omit name/config/enabled independently (e.g. the "toggle
	// enabled" switch sends only enabled).
	UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error)
	// Partial update: any narg left NULL keeps the existing column value, so the
	// handler can omit name/description/status independently.
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	// Partial update: any narg left NULL keeps the existing column value, so the
	// handler can omit name/url/secret/events/enabled independently (e.g. the
	// "toggle enabled" switch sends only enabled).
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error)
}

var _ Querier = (*Queries)(nil)
