// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcdb

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT id, site_title, logo_url, public_status_enabled, updated_at FROM settings WHERE id = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SiteTitle,
		&i.LogoUrl,
		&i.PublicStatusEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
SET site_title            = COALESCE($1, site_title),
    logo_url              = COALESCE($2, logo_url),
    public_status_enabled = COALESCE($3, public_status_enabled),
    updated_at            = now()
WHERE id = 1
RETURNING id, site_title, logo_url, public_status_enabled, updated_at
`

type UpdateSettingsParams struct {
	SiteTitle           *string `json:"site_title"`
	LogoUrl             *string `json:"logo_url"`
	PublicStatusEnabled *bool   `json:"public_status_enabled"`
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRow(ctx, updateSettings, arg.SiteTitle, arg.LogoUrl, arg.PublicStatusEnabled)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.SiteTitle,
		&i.LogoUrl,
		&i.PublicStatusEnabled,
		&i.UpdatedAt,
	)
	return i, err
}
