// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveUser = `-- name: ArchiveUser :exec
UPDATE users SET archived_at = now() WHERE id = $1
`

func (q *Queries) ArchiveUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveUser, id)
	return err
}

const consumeBackupCode = `-- name: ConsumeBackupCode :execrows
UPDATE users
SET totp_backup_codes = array_remove(totp_backup_codes, $2)
WHERE id = $1 AND $2 = ANY(totp_backup_codes)
`

type ConsumeBackupCodeParams struct {
	ID          pgtype.UUID `json:"id"`
	ArrayRemove interface{} `json:"array_remove"`
}

// Atomically removes a backup code only if it is present in the array.
// Returns 1 if consumed, 0 if the code was not found (wrong or already used).
func (q *Queries) ConsumeBackupCode(ctx context.Context, arg ConsumeBackupCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeBackupCode, arg.ID, arg.ArrayRemove)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*) FROM users WHERE role = 'admin' AND archived_at IS NULL
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, role)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, role, created_at, archived_at, totp_secret, totp_enabled, totp_backup_codes
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
	)
	return i, err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE users SET totp_enabled = false, totp_secret = NULL, totp_backup_codes = NULL WHERE id = $1
`

func (q *Queries) DisableTOTP(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableTOTP, id)
	return err
}

const enableTOTP = `-- name: EnableTOTP :exec
UPDATE users SET totp_enabled = true, totp_backup_codes = $2 WHERE id = $1
`

type EnableTOTPParams struct {
	ID              pgtype.UUID `json:"id"`
	TotpBackupCodes []string    `json:"totp_backup_codes"`
}

func (q *Queries) EnableTOTP(ctx context.Context, arg EnableTOTPParams) error {
	_, err := q.db.Exec(ctx, enableTOTP, arg.ID, arg.TotpBackupCodes)
	return err
}

const getTOTPByUserID = `-- name: GetTOTPByUserID :one
SELECT totp_secret, totp_enabled, totp_backup_codes FROM users WHERE id = $1
`

type GetTOTPByUserIDRow struct {
	TotpSecret      *string  `json:"totp_secret"`
	TotpEnabled     bool     `json:"totp_enabled"`
	TotpBackupCodes []string `json:"totp_backup_codes"`
}

func (q *Queries) GetTOTPByUserID(ctx context.Context, id pgtype.UUID) (GetTOTPByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getTOTPByUserID, id)
	var i GetTOTPByUserIDRow
	err := row.Scan(&i.TotpSecret, &i.TotpEnabled, &i.TotpBackupCodes)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, role, created_at, archived_at, totp_secret, totp_enabled, totp_backup_codes FROM users WHERE email = $1 AND archived_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, role, created_at, archived_at, totp_secret, totp_enabled, totp_backup_codes FROM users WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, role, created_at, archived_at, totp_secret, totp_enabled, totp_backup_codes FROM users WHERE archived_at IS NULL ORDER BY created_at
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.TotpBackupCodes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBackupCode = `-- name: RemoveBackupCode :exec
UPDATE users SET totp_backup_codes = array_remove(totp_backup_codes, $2) WHERE id = $1
`

type RemoveBackupCodeParams struct {
	ID          pgtype.UUID `json:"id"`
	ArrayRemove interface{} `json:"array_remove"`
}

func (q *Queries) RemoveBackupCode(ctx context.Context, arg RemoveBackupCodeParams) error {
	_, err := q.db.Exec(ctx, removeBackupCode, arg.ID, arg.ArrayRemove)
	return err
}

const setTOTPSecret = `-- name: SetTOTPSecret :exec
UPDATE users SET totp_secret = $2 WHERE id = $1
`

type SetTOTPSecretParams struct {
	ID         pgtype.UUID `json:"id"`
	TotpSecret *string     `json:"totp_secret"`
}

func (q *Queries) SetTOTPSecret(ctx context.Context, arg SetTOTPSecretParams) error {
	_, err := q.db.Exec(ctx, setTOTPSecret, arg.ID, arg.TotpSecret)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users SET email = $2 WHERE id = $1 AND archived_at IS NULL
RETURNING id, email, password_hash, role, created_at, archived_at, totp_secret, totp_enabled, totp_backup_codes
`

type UpdateUserEmailParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.ID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1 AND archived_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users SET role = $2 WHERE id = $1 AND archived_at IS NULL
RETURNING id, email, password_hash, role, created_at, archived_at, totp_secret, totp_enabled, totp_backup_codes
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.TotpBackupCodes,
	)
	return i, err
}
