// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveWebhook = `-- name: ArchiveWebhook :exec
UPDATE webhooks SET archived_at = now() WHERE id = $1
`

func (q *Queries) ArchiveWebhook(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveWebhook, id)
	return err
}

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (name, url, secret, events)
VALUES ($1, $2, $3, $4)
RETURNING id, name, url, secret, events, enabled, created_at, archived_at
`

type CreateWebhookParams struct {
	Name   string   `json:"name"`
	Url    string   `json:"url"`
	Secret *string  `json:"secret"`
	Events []string `json:"events"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.Events,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, name, url, secret, events, enabled, created_at, archived_at FROM webhooks WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) GetWebhookByID(ctx context.Context, id pgtype.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertWebhookLog = `-- name: InsertWebhookLog :one
INSERT INTO webhook_logs (webhook_id, event, status_code, error, duration_ms)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, webhook_id, event, status_code, error, duration_ms, delivered_at
`

type InsertWebhookLogParams struct {
	WebhookID  pgtype.UUID `json:"webhook_id"`
	Event      string      `json:"event"`
	StatusCode *int32      `json:"status_code"`
	Error      *string     `json:"error"`
	DurationMs *int32      `json:"duration_ms"`
}

func (q *Queries) InsertWebhookLog(ctx context.Context, arg InsertWebhookLogParams) (WebhookLog, error) {
	row := q.db.QueryRow(ctx, insertWebhookLog,
		arg.WebhookID,
		arg.Event,
		arg.StatusCode,
		arg.Error,
		arg.DurationMs,
	)
	var i WebhookLog
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.Event,
		&i.StatusCode,
		&i.Error,
		&i.DurationMs,
		&i.DeliveredAt,
	)
	return i, err
}

const listWebhookLogs = `-- name: ListWebhookLogs :many
SELECT id, webhook_id, event, status_code, error, duration_ms, delivered_at FROM webhook_logs WHERE webhook_id = $1 ORDER BY delivered_at DESC LIMIT $2
`

type ListWebhookLogsParams struct {
	WebhookID pgtype.UUID `json:"webhook_id"`
	Limit     int32       `json:"limit"`
}

func (q *Queries) ListWebhookLogs(ctx context.Context, arg ListWebhookLogsParams) ([]WebhookLog, error) {
	rows, err := q.db.Query(ctx, listWebhookLogs, arg.WebhookID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookLog{}
	for rows.Next() {
		var i WebhookLog
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Event,
			&i.StatusCode,
			&i.Error,
			&i.DurationMs,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooks = `-- name: ListWebhooks :many
SELECT id, name, url, secret, events, enabled, created_at, archived_at FROM webhooks WHERE archived_at IS NULL ORDER BY created_at
`

func (q *Queries) ListWebhooks(ctx context.Context) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksByEvent = `-- name: ListWebhooksByEvent :many
SELECT id, name, url, secret, events, enabled, created_at, archived_at FROM webhooks
WHERE enabled = true AND archived_at IS NULL AND $1::text = ANY(events)
`

func (q *Queries) ListWebhooksByEvent(ctx context.Context, dollar_1 string) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksByEvent, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks
SET name    = COALESCE($2, name),
    url     = COALESCE($3, url),
    secret  = COALESCE($4, secret),
    events  = COALESCE($5, events),
    enabled = COALESCE($6, enabled)
WHERE id = $1
RETURNING id, name, url, secret, events, enabled, created_at, archived_at
`

type UpdateWebhookParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    *string     `json:"name"`
	Url     *string     `json:"url"`
	Secret  *string     `json:"secret"`
	Events  []string    `json:"events"`
	Enabled *bool       `json:"enabled"`
}

// Partial update: any narg left NULL keeps the existing column value, so the
// handler can omit name/url/secret/events/enabled independently (e.g. the
// "toggle enabled" switch sends only enabled).
func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.Enabled,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
